google:
  client-id: 642851971070-8rvc07o3neij0abneq2n0bb7hinbbo1e.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: "http://localhost:8080/auth/login"

spring:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/board"
    username: root
    password: nohj2689
    driver-class-name: com.mysql.cj.jdbc.Driver